In [27]:
import pandas as pd, matplotlib.pyplot as plt, numpy as np

In [28]:
df = pd.read_csv('../data/hotel_booking_clean.csv')
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,3,No Deposit,0.0,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,4,No Deposit,0.0,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,0,No Deposit,0.0,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,0,No Deposit,304.0,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,0,No Deposit,240.0,0,Transient,98.0,0,1,Check-Out,2015-07-03

## Objectives

* Remove the negative value in ADR
* Merge weekend+ weekdays as total_stay
* Merge adults + children + babies as total_attendance
* Keep the selected features

### Remove Negative Value in ADR

In [29]:
df[df['adr'] < 0]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
14529,Resort Hotel,0,195,2017,March,10,5,4,6,2,...,2,No Deposit,273.0,0,Transient-Party,-6.38,0,0,Check-Out,2017-03-15

In [30]:
df = df[df['adr'] > 0].copy()

In [31]:
df['adr'].min()

np.float64(0.26)

### Merge Weekend + WeekDays as total_stay

In [32]:
df['total_stay'] = (df['stays_in_weekend_nights'] + df['stays_in_week_nights'])

In [33]:
df[['total_stay', 'stays_in_weekend_nights','stays_in_week_nights']].head()

   total_stay  stays_in_weekend_nights  stays_in_week_nights
2           1                        0                     1
3           1                        0                     1
4           2                        0                     2
5           2                        0                     2
6           2                        0                     2

In [34]:
df.drop(columns=['stays_in_weekend_nights','stays_in_week_nights'], inplace=True)

### Merge babies + adults + children as total_attendance

In [35]:
df['total_attendance'] = (df['babies'] + df['adults'] + df['children']).astype(int)

In [36]:
df[['total_attendance', 'babies','adults','children']].head()

   total_attendance  babies  adults  children
2                 1       0       1       0.0
3                 1       0       1       0.0
4                 2       0       2       0.0
5                 2       0       2       0.0
6                 2       0       2       0.0

In [37]:
df.drop(columns=['babies','adults','children'], inplace=True)

### Keep the selected features

In [39]:
selected_features = [
    "is_canceled",
    "lead_time",
    "arrival_date_week_number",
    "arrival_date_day_of_month",
    "total_stay",
    "total_attendance",
    "meal",
    "country",
    "market_segment",
    "reserved_room_type",
    "assigned_room_type",
    "deposit_type",
    "adr",
    "total_of_special_requests"
]

df = df[selected_features]

In [40]:
df.head()

,is_canceled,lead_time,arrival_date_week_number,arrival_date_day_of_month,total_stay,total_attendance,meal,country,market_segment,reserved_room_type,assigned_room_type,deposit_type,adr,total_of_special_requests
2,0,7,27,1,1,1,BB,GBR,Direct,A,C,No Deposit,75.0,0
3,0,13,27,1,1,1,BB,GBR,Corporate,A,A,No Deposit,75.0,0
4,0,14,27,1,2,2,BB,GBR,Online TA,A,A,No Deposit,98.0,1
5,0,14,27,1,2,2,BB,GBR,Online TA,A,A,No Deposit,98.0,1
6,0,0,27,1,2,2,BB,PRT,Direct,C,C,No Deposit,107.0,0

### Modelling the Dataset

In [46]:
y = df['is_canceled']
x = df.drop(columns = ['is_canceled'])

### Enocding